CREATE DATABASE IF NOT EXISTS makemytrip_clone
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE makemytrip_clone;

CREATE TABLE IF NOT EXISTS cities (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(3) NOT NULL UNIQUE,
  name VARCHAR(120) NOT NULL,
  airport VARCHAR(255) NOT NULL,
  country VARCHAR(120) NOT NULL,
  group_name VARCHAR(120) NOT NULL DEFAULT 'Popular Cities',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  display_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX ix_cities_code (code),
  INDEX ix_cities_name (name),
  INDEX ix_cities_country (country),
  INDEX ix_cities_group_name (group_name)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS product_tabs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tab_key VARCHAR(40) NOT NULL UNIQUE,
  label VARCHAR(80) NOT NULL,
  icon VARCHAR(40) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  is_new BOOLEAN NOT NULL DEFAULT FALSE,
  display_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS fare_types (
  id INT AUTO_INCREMENT PRIMARY KEY,
  fare_key VARCHAR(40) NOT NULL UNIQUE,
  label VARCHAR(80) NOT NULL,
  description VARCHAR(160) NOT NULL,
  price_multiplier DECIMAL(8,4) NOT NULL DEFAULT 1.0000,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  display_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS homepage_content (
  id INT AUTO_INCREMENT PRIMARY KEY,
  page_key VARCHAR(40) NOT NULL UNIQUE DEFAULT 'home',
  hero_eyebrow VARCHAR(120) NOT NULL,
  hero_title VARCHAR(160) NOT NULL,
  hero_subtitle VARCHAR(255) NOT NULL,
  hero_alert VARCHAR(160) NOT NULL,
  advisory_title VARCHAR(120) NOT NULL,
  advisory_body VARCHAR(255) NOT NULL,
  advisory_cta_label VARCHAR(80) NOT NULL,
  download_eyebrow VARCHAR(80) NOT NULL,
  download_title VARCHAR(160) NOT NULL,
  download_body TEXT NOT NULL,
  app_store_url VARCHAR(500) NOT NULL,
  play_store_url VARCHAR(500) NOT NULL,
  phone_mockup_route VARCHAR(60) NOT NULL,
  offer_title VARCHAR(120) NOT NULL,
  offer_code VARCHAR(40) NOT NULL,
  company_address VARCHAR(255) NOT NULL,
  about_title VARCHAR(120) NOT NULL,
  about_body TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS footer_directories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(80) NOT NULL,
  icon VARCHAR(40) NOT NULL,
  display_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS footer_links (
  id INT AUTO_INCREMENT PRIMARY KEY,
  directory_id INT NOT NULL,
  label VARCHAR(120) NOT NULL,
  href VARCHAR(500) NOT NULL DEFAULT '#',
  display_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_footer_links_directory
    FOREIGN KEY (directory_id) REFERENCES footer_directories(id)
    ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS brand_trust_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  trust_key VARCHAR(80) NOT NULL UNIQUE,
  title VARCHAR(120) NOT NULL,
  body VARCHAR(255) NOT NULL,
  image_url VARCHAR(500) NOT NULL,
  display_order INT NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS offers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  offer_key VARCHAR(80) NOT NULL UNIQUE,
  category VARCHAR(40) NOT NULL,
  title VARCHAR(180) NOT NULL,
  subtitle VARCHAR(180) NOT NULL,
  description TEXT NOT NULL,
  promo_code VARCHAR(40) NOT NULL,
  image_url VARCHAR(500) NOT NULL,
  expiry VARCHAR(80) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  display_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX ix_offers_category (category)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS airlines (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(12) NOT NULL UNIQUE,
  name VARCHAR(120) NOT NULL,
  logo_url VARCHAR(500) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS flights (
  id INT AUTO_INCREMENT PRIMARY KEY,
  flight_key VARCHAR(80) NOT NULL UNIQUE,
  airline_id INT NOT NULL,
  flight_number VARCHAR(40) NOT NULL,
  departure_time VARCHAR(10) NOT NULL,
  arrival_time VARCHAR(10) NOT NULL,
  duration VARCHAR(40) NOT NULL,
  stops INT NOT NULL DEFAULT 0,
  stop_details VARCHAR(120) NOT NULL,
  base_price INT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  display_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_flights_airline
    FOREIGN KEY (airline_id) REFERENCES airlines(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS flight_travel_classes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  flight_id INT NOT NULL,
  travel_class VARCHAR(40) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_flight_classes_flight
    FOREIGN KEY (flight_id) REFERENCES flights(id)
    ON DELETE CASCADE,
  CONSTRAINT uq_flight_travel_class UNIQUE (flight_id, travel_class)
) ENGINE=InnoDB;
